// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaServicios.API.ShoppingCart.Application.Persistence;

#nullable disable

namespace TiendaServicios.API.ShoppingCart.Migrations
{
    [DbContext(typeof(ContextShoppingCart))]
    partial class ContextShoppingCartModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TiendaServicios.API.ShoppingCart.Application.Model.SessionCart", b =>
                {
                    b.Property<int>("IdSessionCart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdSessionCart");

                    b.ToTable("sessionCart");
                });

            modelBuilder.Entity("TiendaServicios.API.ShoppingCart.Application.Model.SessionCartDetail", b =>
                {
                    b.Property<int>("SessionCartDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SelectedProduct")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SessionCartId")
                        .HasColumnType("int");

                    b.HasKey("SessionCartDetailId");

                    b.HasIndex("SessionCartId");

                    b.ToTable("sessionCartDetail");
                });

            modelBuilder.Entity("TiendaServicios.API.ShoppingCart.Application.Model.SessionCartDetail", b =>
                {
                    b.HasOne("TiendaServicios.API.ShoppingCart.Application.Model.SessionCart", "SessionCart")
                        .WithMany("ListSessionCartDetails")
                        .HasForeignKey("SessionCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionCart");
                });

            modelBuilder.Entity("TiendaServicios.API.ShoppingCart.Application.Model.SessionCart", b =>
                {
                    b.Navigation("ListSessionCartDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
